#pragma once
#include <stdint.h>

typedef enum {
    MSG_HELLO, MSG_PAIR_REQUEST, MSG_PAIR_RESPONSE,
    MSG_SESSION_START, MSG_SESSION_ACK,
    MSG_RANGING_START, MSG_RANGING_STOP, MSG_RANGING_SAMPLE,
    MSG_HEARTBEAT, MSG_ERROR,
    MSG_MOVE_TO, MSG_ZONE_SET, MSG_COVERAGE_UPDATE, MSG_SCHEDULE_SET,
    MSG_UNKNOWN
} message_type_t;

#define ERR_UNKNOWN_MESSAGE     1000
#define ERR_INVALID_SCHEMA      1001
#define ERR_UNSUPPORTED_VERSION 1002
#define ERR_UNAUTHORIZED        1003
#define ERR_SESSION_NOT_FOUND   1004
#define ERR_TIMEOUT             1005
#define ERR_BUSY                1006
#define ERR_RADIO_FAILURE       1007
#define ERR_INTERNAL            1008

#define PROTOCOL_VERSION_SUPPORTED 2
